### ISSUE TITLE
Should Kafka Version in examples be 0.10.0.1

### ISSUE THREAD

**Issue by ashishpok** [pndaproject/example-applications#19]
In examples that are using kafka (eg: spark-streaming) should pom.xml be updated to have 0.10.0.1 version of kafka clients? I believe that is what is being used in platform.

**Comment by jeclarke** [comment]
Sorry for the long delay in answering this question.

Spark streaming 1.6 (spark-streaming-kafka-assembly_2.10) requires a 0.8.2.x kafka-clients library. I'm not 100% clear on whether there are any implications with using this with kafka > 0.8, e.g. 0.10 or 0.11 that PNDA uses now - but I've not encountered any problems.
